name = "UngaBungaPack"
author = "Filiflo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6578281d642bc79bde91a70e1cd14135f0d4c0702eb1f17e6d68ae7019954584"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
