name = "UngaBungaPack"
author = "Filiflo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cbce46b5db8c0931c467189ed71f25160599f2eee06b2522eb24b60d3bf0d18"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
