name = "UngaBungaPack"
author = "Filiflo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1d20c9cc8db8e629b908bb1817ae94583f3ba74de8b758bf2e9dde439310799"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
