name = "UngaBungaPack"
author = "Filiflo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50ccd2490b8c0e3167611802016041722f5144d2d5c4687abb92bec854c57cf5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
