name = "UngaBungaPack"
author = "Filiflo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07d01d8dc4525ed2ff59ebbcb1a4ea7aedc5be3d1499f4b32d3477936704b1d6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
