name = "UngaBunga"
author = "filiflo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f58d4c2ff9053c75dc6cdc0f3ab1e05d8d50464f17100df76d17bcf763429e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.173"
